name: Autograding Tests
on:
  - workflow_dispatch
  - push
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pytest
        id: setup-pytest
        run: |
           python -m pip install --upgrade pip
           pip install pytest

      - name: Check if the required files exist and are not empty
        id: file-check
        run: |
          for file in dessert.py test_dessert.py dessertshop.py test_candy.py test_cookie.py test_icecream.py test_sundae.py; do
            if [ ! -s "$file" ]; then
              echo "Error: Required file $file does not exist or is empty."
              exit 1
            fi
          done

      - name: Check if the main program can run
        id: run-check
        run: |
          python dessertshop.py "$1"
          python_exit_status=$?
          if [ $python_exit_status -ne 0 ]; then
            echo "Python script exited with error code $python_exit_status"
            exit $python_exit_status
          fi

      - name: Run Pytest
        id: pytest
        run: |
          pytest
